import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header'
import './globals.css'
import "@fontsource/dm-sans";
import Image from 'next/image';
// import './utils/utils'


export const metadata: Metadata = {
  title: 'BlockPool',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<body className="bg-[#0f0f0f] bg-[url('/back_img.png')] bg-contain bg-no-repeat" style={{backgroundPosition: '-3px -53px' }}>

      
        <Header />
        {children}
      </body>
    </html>
  )
}
