import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header'
import './globals.css'
import "@fontsource/dm-sans";
// import './utils/utils'


export const metadata: Metadata = {
  title: 'BlockPool',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#0f0f0f] " >
        <Header />
        <div className=" bg-contain   bg-center sm:bg-top  bg-no-repeat" id='custom' style={{backgroundImage: "url('/back_img.png')",
      backgroundPosition: '-7px -56.5px'
      }}>
        {children}
        </div>
       
      </body>
    </html>
  )
}
